# Dockerfile.nginx
FROM nginx:alpine
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.railway.conf /etc/nginx/nginx.conf
EXPOSE 80
# Use a shell command to substitute environment variables in the template
# and output them to /etc/nginx/conf.d/default.conf before starting nginx
CMD ["/bin/sh", "-c", "envsubst '${APP_SERVICE_URL} ${AUTH_SERVICE_URL} ${USER_SERVICE_URL} ${WALLET_SERVICE_URL} ${TRANSACTION_SERVICE_URL} ${KYC_SERVICE_URL} ${FILE_SERVICE_URL} ${NOTIFICATION_SERVICE_URL} ${BILLING_SERVICE_URL} ${ADMIN_SERVICE_URL} ${MINIO_SERVICE_URL}' < /etc/nginx/conf.d/default.conf > /etc/nginx/conf.d/default.conf.processed && mv /etc/nginx/conf.d/default.conf.processed /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"]